# Generated by Django 6.0.7 on 2026-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_order_orderitem_order_products_or_order_n_7c6bc8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="image",
            field=models.ImageField(null=True, upload_to="shoes/"),
        ),
    ]
